repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        args: [ --fix ]
        files: ^(app|tests)/.*\.py$
      - id: ruff-format
        files: ^(app|tests)/.*\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        files: ^app/.*\.py$
        additional_dependencies:
          - pydantic-settings>=2.0.0
          - sqlalchemy>=2.0.0
          - fastapi[standard]>=0.115.13
          - types-requests>=2.31.0

