version: '3.8'

services:
  community-calendar-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:ro
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/events.db
      - AUTH_USERNAME=admin
      - AUTH_PASSWORD=dev_password_123
      - APP_TITLE=Community Events Calendar (Development)
      - APP_DESCRIPTION=Development instance of the community events calendar API
      - CALENDAR_PRODID=-//Community Events Calendar Dev//EN
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8000
    restart: unless-stopped